---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-os-dependency
spec:
  selector:
    matchLabels:
      app: longhorn-os-dependency
  template:
    metadata:
      labels:
        app: longhorn-os-dependency
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: dependency-install
        command: ["/bin/sh"]
        args: ["-c", "nsenter --mount=/proc/1/ns/mnt -- sh -c 'yum -y install iscsi-initiator-utils'"]
        image: alpine:latest
        securityContext:
          privileged: true
      containers:
      - name: pause
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.8