---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: longhorn-terminator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-terminator
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces/finalize
  - namespaces/status
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-terminator
subjects:
- kind: ServiceAccount
  name: longhorn-terminator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: longhorn-terminator
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          serviceAccountName: longhorn-terminator
          containers:
          - name: longhorn-terminator
            image: bitnami/kubectl:1.31.4
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            args:
            - -ec
            - |
              if [[ $(kubectl get namespace longhorn-system -o=jsonpath='{.status.phase}') == Terminating ]];
              then
                kubectl get namespace longhorn-system -o json   | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/"   | kubectl replace --raw /api/v1/namespaces/longhorn-system/finalize -f -
              fi
          restartPolicy: Never
